library(covr)
cov <- package_coverage()
print(cov)
zero_coverage(cov)
report(cov, file = file.path("/workdir/tests/coverage-report.html"), browse = FALSE)
codecov(coverage = cov, token = "4444c90d-ea86-4d95-a467-09ee526dda8e")
